### ISSUE TITLE
train on the base of the pretrained model SiamRPNotb.model 

### ISSUE THREAD

**Issue by zhanght021** [HelloRicky123/Siamese-RPN#13]
can this code train on the base of the pretrained model "SiamRPNotb.model" released by foolwood

**Comment by HelloRicky123** [comment]
yes，you can load the former 3 layers of the SiamRPNotb.model. The setting is in line 54 of the config.py file.

**Comment by zhanght021** [comment]
> yes，you can load the former 3 layers of the SiamRPNotb.model. The setting is in line 54 of the config.py file.

thanks for your code and your answer, and I have another questions 

(1)in the 54version, you didn't freeze the former 3 BN layers, so is there any benefits? 
(2) if I change some code, can I load the full SiamRPNotb.model parameters, and then freeze the former 3 layers, and train on the base of the pretrained parameters
(我可不可以改变一下几行代码，然后把SiamRPNotb.model的所有参数都导入，然后在固定住前三层，在这些已经训练好的参数上训练？)
Thank you very much

**Comment by zhanght021** [comment]
@HelloRicky123  Thanks for your code and your answer, and I have another questions

(1)in the 54version, you didn't freeze the former 3 BN layers, so is there any benefits?
(2) if I change some code, can I load the full SiamRPNotb.model parameters, and then freeze the former 3 layers, and train on the base of the pretrained parameters .In my opinion ,SiamRPBotb.model is enough training, if I want to use in some special scene, can I base the fully model parameters, using some my own template to train
(我可不可以改变一下几行代码，然后把SiamRPNotb.model的所有参数都导入，然后在固定住前三层，在这些已经训练好的参数上训练？因为我想着这个模型已经训练的很充分了，然后我用在比较特定的场景的话，可不可以在他整个模型参数的基础之上，用我自己的一些样本训练)
Thank you very much

**Comment by fAnchao1** [comment]
@zhanght021 你用这个代码能够跑起来嘛，能指导我一下嘛

**Comment by zhanght021** [comment]
@fAnchao1 我还在下载数据集，等下完了试试，应该没问题的吧，作者都已经把结果测出来了

**Comment by fAnchao1** [comment]
可以加个qq？

**Comment by zhanght021** [comment]
@fAnchao1 这个等我明后天自己跑通了再交流，不然到时候就比较尴尬了，哈哈

**Comment by HelloRicky123** [comment]
> @HelloRicky123 Thanks for your code and your answer, and I have another questions
> 
> (1)in the 54version, you didn't freeze the former 3 BN layers, so is there any benefits?
> (2) if I change some code, can I load the full SiamRPNotb.model parameters, and then freeze the former 3 layers, and train on the base of the pretrained parameters .In my opinion ,SiamRPBotb.model is enough training, if I want to use in some special scene, can I base the fully model parameters, using some my own template to train
> (我可不可以改变一下几行代码，然后把SiamRPNotb.model的所有参数都导入，然后在固定住前三层，在这些已经训练好的参数上训练？因为我想着这个模型已经训练的很充分了，然后我用在比较特定的场景的话，可不可以在他整个模型参数的基础之上，用我自己的一些样本训练)
> Thank you very much

Yes, of course. I tried this previously and can get 0.56 auc with code.

**Comment by fAnchao1** [comment]
@HelloRicky123 hello,how can i test the result in the vot-toolkit

**Comment by ghost** [comment]
@HelloRicky123  Thanks for your amazing work. And how to check the results with the vot-toolkit?

**Comment by fAnchao1** [comment]
@zhanght021 你做的怎么样了

**Comment by fAnchao1** [comment]
@longqiwf have you test on vot?

**Comment by stillqueen** [comment]
@fAnchao1 你现在问题解决了吗？要不要加个QQ？

**Comment by fAnchao1** [comment]
@stillqueen 还没有呢，你呢，可以啊加个qq我加你

**Comment by stillqueen** [comment]
@fAnchao1 974765289

**Comment by stillqueen** [comment]
@fAnchao1 上面是我QQ,你可以加一下哈

**Comment by HelloRicky123** [comment]
Closed first.
