### ISSUE TITLE
Where is the dataset_ssd directory?

### ISSUE THREAD

**Issue by fzh0917** [HelloRicky123/Siamese-RPN#18]
I got this error message:
```
FileNotFoundError: [Errno 2] No such file or directory: '/dataset_ssd/ytb_vid_rpn_id/meta_data.pkl'
```
Where is the `dataset_ssd` directory in the `59version`? Should I create a such directory manually and then download the `meta_data.pkl` from the Internet and put it into that directory?

**Comment by fzh0917** [comment]
> I got this error message:
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: '/dataset_ssd/ytb_vid_rpn_id/meta_data.pkl'
> ```
> Where is the `dataset_ssd` directory in the `59version`? Should I create a such directory manually and then download the `meta_data.pkl` from the Internet and put it into that directory?

However, I didn't find the `meta_data.pkl` file in the Internet.

**Comment by HelloRicky123** [comment]
It is created by the bin/create_dataset.py and create_lmdb.py

**Comment by fzh0917** [comment]
OK, thank you. I have understood the steps.

**Comment by HelloRicky123** [comment]
Closed.
