### ISSUE TITLE
what's wrong

### ISSUE THREAD

**Issue by fAnchao1** [HelloRicky123/Siamese-RPN#20]
File "/home/fc/文档/Siamese-RPN-master/59version/lib/utils.py", line 99, in crop_and_pad
    te_im[:, 0:left, :] = img_mean
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by Alex6D** [comment]
I have the same problem. Have you solved it?

**Comment by Jervint** [comment]
I tried to make img_mean!=None and this error had disappeared

**Comment by HelloRicky123** [comment]
Yes, the image maybe small when train the model. And make it bigger in create_*.py will be better.

**Comment by Jervint** [comment]
Whether i can also use the scripts to make datasets from got10k.? I use got10k train net directly and cannot get any correct preditction
发自我的iPhone

------------------ Original ------------------

**Comment by HelloRicky123** [comment]
你可能应该检查一下坐标的对应关系发自我的iPhone------------------ Original ------------------From: Yang Yifeng  <notifications@github.com>Date: Tue,Apr 23,2019 0:04 AMTo: HelloRicky123/Siamese-RPN <Siamese-RPN@noreply.github.com>Cc: HelloRicky123 <qftju12345@163.com>, State change <state_change@noreply.github.com>Subject: Re: [HelloRicky123/Siamese-RPN] what's wrong (#20)Whether i can also use the scripts to make datasets from got10k.? I use got10k train net directly and cannot get any correct preditction

发自我的iPhone



------------------ Original ------------------

**Comment by Jervint** [comment]
谢谢~我去尝试一下。我自己的网络加入了一些特征融合的trick，可能这部分也存在有问题


发自我的iPhone

------------------ Original ------------------
