### ISSUE TITLE
How to prepare YoutubeBB data?

### ISSUE THREAD

**Issue by yiminglin-ai** [HelloRicky123/Siamese-RPN#23]
Hi Ruiqi,
Can you please elaborate how you prepared YoutubeBB before running create_dataset_ytbid.py? How did you download and store it in  /mnt/diska1/YT-BB/v2/youtube_dection_frame_temp/  and /mnt/usershare/zrq/pytorch/lab/model/zhangruiqi/ytb_vid/benchmark.ytbb/xml ? 

Thank you!
Yiming

**Comment by HelloRicky123** [comment]
This part of code is trouble and I have not formatted it by now. You can read the creat_*.py and write it yourself.
