### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by Alex6D** [HelloRicky123/Siamese-RPN#25]
when I run the 59version/train_siamrpn.py

**Comment by stillqueen** [comment]
you can go to the last line of the tracker.py, it return self.bbox and score_pred[best_pscore_id], you can just delete the score_pred[best_pscore_id]

**Comment by HelloRicky123** [comment]
This is because the image is too small in training. You can modify the dataset.py to fix it. Just add padding when crop image.

**Comment by GengMingjin2** [comment]
@Alex6D Have you sovled the problem? I just read the code of "crop_and_pad" in "lib/util.py", but I can't figure out how to "pad"... I am new in such a project. It's glad that you can help me.
