### ISSUE TITLE
data processing

### ISSUE THREAD

**Issue by Manguotree** [HelloRicky123/Siamese-RPN#33]
Hi Thank you for the code. You generated meta_data.pkl file in create_dataset_ytbid with youtobe and ILSVRC2015, but since the YouTubeBB dataset I got has been processed and has a separate meta_data.pkl. So what do I do next before I run create_lmdb.py? Can I combine their meta_data.pkl directly? Or do I set --data-dir to two paths? I hope you can give me some advice. Thank you very much！

**Comment by HelloRicky123** [comment]
Maybe the your meta_data have the different format to mine. So I advice to understand the dataset code firstly. Or use vid without youtube data. And I will upload the processed data in a couple of days. The whole data is of 145 G.

**Comment by Manguotree** [comment]
Thank you very much for your reply. I have read your code and generated youtubebb's LMDB file through create_lmdb.py, but it is not combined with the ILSVRC data set (does this mean that the processed youtubebb data format I got is the same as your ?) .Looking forward to your upcoming data



------------------ 原始邮件 ------------------
发件人: "HelloRicky123"<notifications@github.com>;
发送时间: 2019年5月9日(星期四) 晚上9:19
收件人: "HelloRicky123/Siamese-RPN"<Siamese-RPN@noreply.github.com>;
抄送: "minemine"<1336462834@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [HelloRicky123/Siamese-RPN] data processing (#33)




Maybe the your meta_data have the different format to mine. So I advice to understand the dataset code firstly. Or use vid without youtube data. And I will upload the processed data in a couple of days. The whole data is of 145 G.

**Comment by chengxianda54321** [comment]
> Hi Thank you for the code. You generated meta_data.pkl file in create_dataset_ytbid with youtobe and ILSVRC2015, but since the YouTubeBB dataset I got has been processed and has a separate meta_data.pkl. So what do I do next before I run create_lmdb.py? Can I combine their meta_data.pkl directly? Or do I set --data-dir to two paths? I hope you can give me some advice. Thank you very much！

hello, how to get your youtube-bb dataset? thank you
