### ISSUE TITLE
ModuleNotFoundError: No module named 'siamfc'

### ISSUE THREAD

**Issue by fzh0917** [HelloRicky123/Siamese-RPN#41]
In your `bin/demo_siamrpn.py` file, there is one line code which likes:
```
from siamfc import SiamRPNTracker
```
Can you provide the `siamfc` module so that we can run your code more easily?

**Comment by fzh0917** [comment]
> In your `bin/demo_siamrpn.py` file, there is one line code which likes:
> 
> ```
> from siamfc import SiamRPNTracker
> ```
> 
> Can you provide the `siamfc` module so that we can run your code more easily?

**Comment by utkarsh-mishra9** [comment]
I encountered a similar problem and I am not able to solve it
