### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'siamfc'

### ISSUE THREAD

**Issue by fzh0917** [HelloRicky123/Siamese-RPN#42]
In your `bin/demo_siamrpn.py` file, there is one line code which likes:
```
from siamfc import SiamRPNTracker
```
Can you provide the `siamfc` module so that we can run your code more easily?

**Comment by fzh0917** [comment]
> In your `bin/demo_siamrpn.py` file, there is one line code which likes:
> 
> ```
> from siamfc import SiamRPNTracker
> ```
> 
> Can you provide the `siamfc` module so that we can run your code more easily?

I can't understand the reason why the `SiamRPNTracker` module was put in the `siamfc` folder or file.

**Comment by HelloRicky123** [comment]
This code is modified from an implementation of SiamFC. And the demo code is not maintained.
