### ISSUE TITLE
Does VOT support pytorch1.0 ？

### ISSUE THREAD

**Issue by TSSSS4** [HelloRicky123/Siamese-RPN#5]
Your PyTorch version is 1.0, is that supported by VOT toolkit ?  In my case, some errors occured when using PyTorch 0.4.1, and only 0.3.1 works well.

**Comment by HelloRicky123** [comment]
I use 1.0 for training, and use 0.3.1 for testing on vot.

**Comment by HelloRicky123** [comment]
Closed
