### ISSUE TITLE
fix former 3 conv layer

### ISSUE THREAD

**Issue by charlesyann** [HelloRicky123/Siamese-RPN#6]
hello,
Two questions for training:
   1.  Did you freeze the last convolution layer too in training phase?
        keys_former3conv = ['featureExtract.0.weight', 'featureExtract.0.bias', 'featureExtract.1.weight',
                            'featureExtract.1.bias', 'featureExtract.1.running_mean', 'featureExtract.1.running_var',
                            'featureExtract.4.weight', 'featureExtract.4.bias', 'featureExtract.5.weight',
                            'featureExtract.5.bias', 'featureExtract.5.running_mean', 'featureExtract.5.running_var',
                            'featureExtract.8.weight', 'featureExtract.8.bias', 'featureExtract.9.weight',
                            'featureExtract.9.bias', 'featureExtract.9.running_mean', 'featureExtract.9.running_var']

   2.   What's the meaning of set track_running_stats to false if you have set required_grad to false?
        'model.featureExtract[layer].track_running_stats = False',

**Comment by HelloRicky123** [comment]
2, it will make the running mean and var fixed.

**Comment by longchaoyang** [comment]
thank u for your reponse, for 1, did you also freeze the last conv layer of the feature extract?

**Comment by charlesyann** [comment]
> 
> 
> 2, it will make the running mean and var fixed.

but as far as i know, set required_grad to false will also make running mean and var fixed, yes?

**Comment by HelloRicky123** [comment]
Check the doc of pytorch or some blog
