### ISSUE TITLE
is it a bug when get gt_cx or gt_cy less than zero

### ISSUE THREAD

**Issue by gjpicker** [HelloRicky123/Siamese-RPN#8]
ground_truth's cx cy ,some time  less than zero 

 do some change to return with bbox info in siamfc/dataset.py 
"origin:"--->"add bbox return:"
```
def __getitem__(self,index):
     return exemplar_img, instance_img, regression_target, conf_target.astype(np.int64)

--->

def __getitem__(self,index):
     return exemplar_img, instance_img, regression_target, conf_target.astype(np.int64),\
gt_cx,gt_cy ,gt_w, gt_h
```

then debug bbox detail by print twice  
```

gt_cx,gt_cy ,gt_w, gt_h :: tensor([8.], dtype=torch.float64) tensor([-2.], dtype=torch.float64) \
tensor([83.1059], dtype=torch.float64) tensor([49.2817], dtype=torch.float64)

gt_cx,gt_cy ,gt_w, gt_h :: tensor([6.], dtype=torch.float64) tensor([7.5000], dtype=torch.float64)\
 tensor([76.8523], dtype=torch.float64) tensor([43.6093], dtype=torch.float64)
```

the error's occured position maybe at RandomCrop ,where  "gt_cx = cx_o - cx" at line 136 ,line 137  
[problem in here](https://github.com/HelloRicky123/Siamese-RPN/blob/ee2f5fa458a482c08a12b96dd6c0455c84f34b4d/siamfc/dataset.py#L136)

**Comment by HelloRicky123** [comment]
It is the shift to the center.
